name = "vaultscope"

compatibility_date = "2025-10-15"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[assets]
directory = "./out"